name: weather_flutter
description: 基于和风天气API开发的跨平台天气工具 Cloudbranch
publish_to: 'none'
version: 0.0.20

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  path_provider_linux: ^2.2.1
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  url_launcher: ^6.1.14
  intl: ^0.18.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - CHANGELOG.md
    - CHANGELOG_ANDROID.md
